//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Resource.rc
//
#define IDD_MAINCONTROL                 101
#define IDD_PLAYCONTROL_SLIDE           102
#define IDD_ABOUT                       103
#define IDD_CONFIG                      105
#define IDD_CONFIG_2                    106
#define IDD_VRC6                        107
#define IDD_CHANNELS                    108
#define IDD_GENERALFILEINFO             109
#define IDD_TRACKINFO                   110
#define IDD_PLAYLISTINFO                111
#define IDD_FILEINFO                    112
#define IDD_MMC5                        113
#define IDD_MINIPLAY                    114
#define IDI_WBWINAMP                    115
#define IDD_N106                        115
#define IDD_VRC7                        116
#define IDD_FME07                       117
#define IDD_CONFIG_3                    118
#define IDD_TAGINFO                     119
#define IDC_TAB                         1001
#define IDC_CLIENTBOX                   1002
#define IDB_LOGO                        1002
#define IDC_FILEINFO                    1003
#define IDC_PLAYSLIDER                  1004
#define IDC_PREV                        1005
#define IDC_PLAY                        1006
#define IDC_NEXT                        1007
#define IDC_TRACKTEXT                   1008
#define IDC_SAMPLERATE                  1009
#define IDC_BPS                         1010
#define IDC_STEREO                      1011
#define IDC_IRQMODE                     1013
#define IDC_FASTSEEK                    1014
#define IDC_DISPLAYTIME                 1015
#define IDC_PLAYBACK                    1016
#define IDC_MASTERVOL                   1017
#define IDC_IDEALTRI                    1018
#define IDC_HIGHPASSBAR                 1018
#define IDC_LOWPASS                     1019
#define IDC_MULTISAMPLE                 1020
#define IDC_PREPASS                     1020
#define IDC_OPEN_MULTI                  1021
#define IDC_OPEN_SINGLE                 1022
#define IDC_OPEN_SHADOW                 1023
#define IDC_DEFAULTSPEED                1024
#define IDC_SPEEDTHROTTLE               1025
#define IDC_SPEEDDISPLAY                1026
#define IDC_LOOPFOREVER                 1027
#define IDC_VOLUMEDISPLAY               1027
#define IDC_FORMAT_MULTI                1028
#define IDC_LOWPASSBAR                  1028
#define IDC_FORMAT_SINGLE               1029
#define IDC_PREPASSBAR                  1029
#define IDC_FORMAT_SHADOW               1030
#define IDC_DISABLEPLAYLIST             1031
#define IDC_DEFAULTLENGTH               1032
#define IDC_DEFAULTFADE                 1033
#define IDC_MIX_1                       1033
#define IDC_MIX_2                       1034
#define IDC_MIX_3                       1035
#define IDC_FILENAME                    1036
#define IDC_MIX_4                       1036
#define IDC_CONVERT                     1037
#define IDC_MIX_5                       1037
#define IDC_WINAMPSHADOW                1038
#define IDC_MIX_6                       1038
#define IDC_FILESHADOW                  1039
#define IDC_TRACKLIST                   1039
#define IDC_MIX_7                       1039
#define IDC_LABEL                       1040
#define IDC_PLAYLIST                    1040
#define IDC_MIX_8                       1040
#define IDC_HASLABELS                   1041
#define IDC_VOL_1                       1041
#define IDC_HASLENGTH                   1042
#define IDC_VOL_2                       1042
#define IDC_HASFADE                     1043
#define IDC_VOL_3                       1043
#define IDC_LENGTH                      1044
#define IDC_VOL_4                       1044
#define IDC_FADE                        1045
#define IDC_VOL_5                       1045
#define IDC_GETLENGTH                   1046
#define IDC_VOL_6                       1046
#define IDC_GETFADE                     1047
#define IDC_VOL_7                       1047
#define IDC_VOL_8                       1048
#define IDC_REMOVEALL                   1049
#define IDC_PAN_1                       1049
#define IDC_ADDALL                      1050
#define IDC_PAN_2                       1050
#define IDC_REMOVE                      1051
#define IDC_PAN_3                       1051
#define IDC_MOVEUP                      1052
#define IDC_PAN_4                       1052
#define IDC_ADD                         1053
#define IDC_CLIENTRECT                  1053
#define IDC_PAN_5                       1053
#define IDC_MOVEDOWN                    1054
#define IDC_PAN_6                       1054
#define IDC_SAVE                        1055
#define IDC_PAN_7                       1055
#define IDC_SAVECLOSE                   1056
#define IDC_SHADOWTEXT                  1056
#define IDC_PAN_8                       1056
#define IDC_SLICKPRODUCTIONS            1057
#define IDC_VOLBOX_1                    1057
#define IDC_SUBCLASSWINAMP              1058
#define IDC_VOLBOX_2                    1058
#define IDC_ALWAYSONTOP                 1059
#define IDC_VOLBOX_3                    1059
#define IDC_VOLBOX_4                    1060
#define IDC_VOLBOX_5                    1061
#define IDC_TRACKLABEL                  1062
#define IDC_VOLBOX_6                    1062
#define IDC_USEMINI                     1063
#define IDC_VOLBOX_7                    1063
#define IDC_MINIALWAYSONTOP             1064
#define IDC_VOLBOX_8                    1064
#define IDC_PANBOX_1                    1065
#define IDC_PANBOX_2                    1066
#define IDC_PANBOX_3                    1067
#define IDC_PANBOX_4                    1068
#define IDC_PANBOX_5                    1069
#define IDC_PANBOX_6                    1070
#define IDC_PANBOX_7                    1071
#define IDC_PANBOX_8                    1072
#define IDC_DMCPOPREDUCER               1073
#define IDC_IGNORE4011                  1074
#define IDC_INV_1                       1075
#define IDC_N106POPREDUCER              1076
#define IDC_INV_2                       1077
#define IDC_RESETDUTY                   1077
#define IDC_FORCE4017                   1078
#define IDC_INV_3                       1079
#define IDC_FDSPOPREDUCER               1079
#define IDC_INV_4                       1080
#define IDC_INV_5                       1081
#define IDC_SILENCETRACK                1082
#define IDC_INV_6                       1083
#define IDC_HIGHPASS                    1083
#define IDC_SILENCETRACKMS              1084
#define IDC_HIGHPASSON                  1084
#define IDC_INV_7                       1085
#define IDC_LOWPASSON                   1085
#define IDC_CONFIG                      1085
#define IDC_INVERTCUTOFF                1086
#define IDC_PREPASSON                   1086
#define IDC_IGNOREBRK                   1087
#define IDC_INV_8                       1088
#define IDC_NOSILENCEIFLEN              1088
#define IDC_INVERTCUTOFFHZ              1089
#define IDC_TITLE                       1089
#define IDC_IGNOREILLEGAL               1090
#define IDC_ARTIST                      1090
#define IDC_NOWAIT                      1091
#define IDC_COPYRIGHT                   1091
#define IDC_CLEANAXY                    1092
#define IDC_RIPPER                      1092
#define IDC_PREFERPAL                   1093
#define IDC_CLEANAXY2                   1093
#define IDC_IGNOREVERSION               1093

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        116
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1090
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
